//Login
export const ON_LOGGING = 'ON_LOGGING'
export const UPDATE_LOGIN_PHONENUMBER = 'UPDATE_LOGIN_PHONENUMBER'
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_STORE = 'UPDATE_STORE'
export const UPDATE_REGISTER_STORENAME = 'UPDATE_REGISTER_STORENAME'


//Register

export const UPDATE_REGISTER_PHONENUMBER = 'UPDATE_REGISTER_PHONENUMBER'
export const UPDATE_REGISTER_FIRSTNAME = 'UPDATE_REGISTER_FIRSTNAME'
export const UPDATE_REGISTER_LASTNAME = 'UPDATE_REGISTER_LASTNAME'
export const UPDATE_REGISTER_PASSWORD = 'UPDATE_REGISTER_PASSWORD'


//Home
export const UPDATE_HOME_PHONENUMBER = 'UPDATE_HOME_PHONENUMBER'
export const UPDATE_HOME_SEATS = 'UPDATE_HOME_SEATS'

//Profile

export const UPDATE_PROFILE_STORENAME = 'UPDATE_PROFILE_STORENAME'
export const UPDATE_PROFILE_ESTMIN = 'UPDATE_PROFILE_ESTMIN'