//Login
export const ON_LOGGING = 'ON_LOGGING'
export const UPDATE_LOGIN_PHONENUMBER = 'UPDATE_LOGIN_PHONENUMBER'
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD'


//Register

export const UPDATE_REGISTER_PHONENUMBER = 'UPDATE_REGISTER_PHONENUMBER'
export const UPDATE_REGISTER_FIRSTNAME = 'UPDATE_REGISTER_FIRSTNAME'
export const UPDATE_REGISTER_LASTNAME = 'UPDATE_REGISTER_LASTNAME'
export const UPDATE_REGISTER_PASSWORD = 'UPDATE_REGISTER_PASSWORD'

